### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by deadcoder0904** [downwindcss/text-decoration#9]
I have added the plugin to `tailwind.config.js` & I'm trying to make it work but it isn't. Not sure what I'm doing wrong but here's the code:

```tsx
<a
	className={clsx(
		'px-2 text-lg sm:text-lg',
		pathname === href
			? 'font-extrabold text-blue-gray-700 underline text-decoration-yellow-500 hover:text-blue-gray-500 dark:text-blue-gray-300 hover:dark:text-decoration hover:dark:text-decoration-yellow-500'
			: 'font-semibold text-blue-gray-500 hover:text-blue-gray-700 hover:font-extrabold'
	)}
>
	{title}
</a>
```

I did try on both `light` mode plus `dark` mode but doesn't work anywhere. Just shows me a `white` underline due to the Tailwind class `underline`. What am I doing wrong?

**Comment by dance2die** [comment]
Thank for reporting the issue @deadcoder0904.

I will work on fixing the variant generation issue.
Could you use [JIT mode](https://tailwindcss.com/docs/just-in-time-mode#enabling-jit-mode) if possible for now?

**Comment by dance2die** [comment]
Hi @deadcoder0904.

I released an alpha version, https://www.npmjs.com/package/@downwindcss/text-decoration/v/1.0.3-alpha.0

Can you try this [demo](https://stackblitz.com/edit/nextjs-bz8p2d?file=pages%2Findex.js) (using the alpha version) to see if it'd work for your project?

(__I will release it as "latest" if it works well__)

Note: You need to "enable" variants for "dark", "hover", "responsive". Without the configuration, only "responsive" variant is enabled.

**tailwindcss.config.js**
```js
module.exports = {
  ...
  variants: {
    extend: {
      textDecorationPlugin: ['hover', 'dark', 'responsive']
    }
  },
  plugins: [
    require('@downwindcss/text-decoration')
  ]
};
```

And also you need to add `text-decoration` before conditional statements, not for `dark:text-decoration` only.

```jsx
<a
  href="/"
  className={clsx(
    {*                                        👇  *}
    'px-2 text-lg sm:text-lg block text-decoration',
    isOn
      ? `font-extrabold text-gray-700 
          text-decoration-red-500 text-decoration-underline
          text-decoration-8
          dark:hover:text-gray-500 dark:text-gray-300 
          dark:hover:text-decoration-blue-500`
      : `font-semibold text-gray-500 hover:text-gray-700 hover:font-extrabold`
  )}
>
  Some title here
</a>
```

**Comment by deadcoder0904** [comment]
@dance2die I'll try that. I just had my Mac black out (possibly forever) so I'm on another PC so it'll take time as I didn't push the commits yesterday. 

In the meantime, I need to ask why do we need `text-decoration`? Check out Adam Wathan's new feature on Tailwind where he found a workaround to let people use `translate`, `rotate`, & `skew` without having to specify `transform`. I suppose this can be solved similarly.

And I am already using JIT mode. Not sure how it helps here?

**Comment by dance2die** [comment]
> n the meantime, I need to ask why do we need `text-decoration`? Check out Adam Wathan's new feature on Tailwind where he found a workaround to let people use `translate`, `rotate`, & `skew` without having to specify `transform`. I suppose this can be solved similarly.

Sounds like a plan for the next release :)

> And I am already using JIT mode. Not sure how it helps here?

because I didn't add code to generate according to responsive variants. JIT mode will, even though plugin didn't implement the variant.
